/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Bank;

import java.io.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.xml.transform.OutputKeys;

/**
 *
 * @author HP
 */
public class Data extends javax.swing.JFrame {

    /**
     * Creates new form Data
     */
    public Data() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cnic = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        openingBalance = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Pin = new javax.swing.JPasswordField();
        occupation = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel2.setText("APPLICATION FORM");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 0, 291, 70));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 2, 16)); // NOI18N
        jLabel1.setText("Your Full Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 113, 173, -1));

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nameKeyPressed(evt);
            }
        });
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 148, 230, 38));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 2, 15)); // NOI18N
        jLabel3.setText("CNIC");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 204, 213, 29));

        cnic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cnicKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cnicKeyReleased(evt);
            }
        });
        getContentPane().add(cnic, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 243, 230, 37));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 2, 15)); // NOI18N
        jLabel4.setText("Enter your Age");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 383, 230, 34));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 2, 15)); // NOI18N
        jLabel5.setText("Occupation");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 295, 230, 33));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 2, 15)); // NOI18N
        jLabel6.setText("Account Type");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 106, 175, 36));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CURRENT ACCOUNT", "SAVING ACCOUNT", "INVESTMENT ACCOUNT" }));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 148, 175, 38));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 2, 15)); // NOI18N
        jLabel7.setText("Investment Period");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 208, -1, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 year", "3 Year", "5 Year" }));
        getContentPane().add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 239, 135, 44));

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 2, 15)); // NOI18N
        jLabel8.setText("Initial Deposit");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 295, 135, 33));

        openingBalance.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                openingBalanceKeyPressed(evt);
            }
        });
        getContentPane().add(openingBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 334, 175, 36));

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 2, 15)); // NOI18N
        jLabel9.setText("PIN");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 385, 175, 31));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 559, -1, 33));

        jButton2.setFont(new java.awt.Font("Segoe UI Black", 1, 17)); // NOI18N
        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 547, 145, 45));

        Pin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PinActionPerformed(evt);
            }
        });
        Pin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PinKeyPressed(evt);
            }
        });
        getContentPane().add(Pin, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 425, 109, 32));

        occupation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                occupationActionPerformed(evt);
            }
        });
        occupation.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                occupationKeyPressed(evt);
            }
        });
        getContentPane().add(occupation, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 334, 230, 36));

        age.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ageKeyPressed(evt);
            }
        });
        getContentPane().add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 424, 230, 34));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bank/dataPic(1).jpg"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void occupationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_occupationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_occupationActionPerformed

    private void cnicKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cnicKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_cnicKeyReleased

    private void nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyPressed
        // TODO add your handling code here:
        char c =evt.getKeyChar();
        
        if (Character.isLetter(c) || Character.isWhitespace(c)|| Character.isISOControl(c)) {
            name.setEditable(true);
        }
        else name.setEditable(false);
    }//GEN-LAST:event_nameKeyPressed

    private void cnicKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cnicKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        String s = cnic.getText();
        
        if (s.length()>9 && !Character.isISOControl(c)) {
            cnic.setEditable(false);
        }
        else if (Character.isDigit(c) || Character.isISOControl(c)) {
            cnic.setEditable(true);
        }
        else cnic.setEditable(false);
    }//GEN-LAST:event_cnicKeyPressed

    private void ageKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ageKeyPressed
        // TODO add your handling code here:
        char c= evt.getKeyChar();
         String s = age.getText();
         
        if (s.length()>2 && !Character.isISOControl(c)) {
            age.setEditable(false);
        }
        else if (Character.isDigit(c) || Character.isISOControl(c)) {
            age.setEditable(true);
        }
        else age.setEditable(false);
        
    }//GEN-LAST:event_ageKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new options().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void openingBalanceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_openingBalanceKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        
        if (Character.isDigit(c) || Character.isISOControl(c)) {
            openingBalance.setEditable(true);
        }
        else openingBalance.setEditable(false);
    }//GEN-LAST:event_openingBalanceKeyPressed

    private void PinKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PinKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        
        if (Character.isDigit(c) || Character.isISOControl(c)) {
            Pin.setEditable(true);
        }
        else Pin.setEditable(false);
    }//GEN-LAST:event_PinKeyPressed

    private void occupationKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_occupationKeyPressed
        // TODO add your handling code here:
        char c =evt.getKeyChar();
        
        if (Character.isLetter(c) || Character.isWhitespace(c)|| Character.isISOControl(c)) {
            occupation.setEditable(true);
        }
        else occupation.setEditable(false);
    }//GEN-LAST:event_occupationKeyPressed

    private void PinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PinActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        // Checking if some Textfield is left empty by the User
        if (name.getText().trim().isEmpty() || cnic.getText().trim().isEmpty()  
            || occupation.getText().trim().isEmpty() || age.getText().trim().isEmpty() 
            || openingBalance.getText().trim().isEmpty() || Pin.getText().trim().isEmpty()) {
            
             JOptionPane.showMessageDialog(Data.this, "Please enter the information in all fields");
            return;
        }
        else{
            String name = this.name.getText();
            Long cnic = Long.parseLong(this.cnic.getText());
            String Occupation = occupation.getText();
            int Age = Integer.parseInt(age.getText());
            String Type = jComboBox2.getSelectedItem().toString();
            String Period = jComboBox3.getSelectedItem().toString();
            double balance = Double.parseDouble(openingBalance.getText());
            int pin = Integer.parseInt(Pin.getText());
            
            Account account = new Account(cnic, name, Age, Occupation, Type, Period, balance,pin);
            
            ArrayList<Account> List = new ArrayList<>();
            
            FileInputStream fin;
            ObjectInputStream in;
            
             // DeSerialzing ArrayList
            try{
            fin = new FileInputStream(new File("Accounts.txt"));
            in = new ObjectInputStream(fin);
            
            List = (ArrayList) in.readObject();
            }
            catch(FileNotFoundException e ){
                System.out.println(e);
            }
            catch(IOException e){
                System.out.println(e);
            }
            catch(ClassNotFoundException e){
                System.out.println(e);
            }
            
            List.add(account);
            FileOutputStream fout;
            ObjectOutputStream obj;
            try{
             fout = new FileOutputStream(new File("Accounts.txt"));
             obj = new ObjectOutputStream(fout);
             obj.writeObject(List);
             fout.close(); obj.close();
            }
            catch(IOException e){
                System.out.println(e);
            }
        }
        JOptionPane.showMessageDialog(Data.this, "Account Created Successfully");
        
       new options().setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])  {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Data().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Pin;
    private javax.swing.JTextField age;
    private javax.swing.JTextField cnic;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField name;
    private javax.swing.JTextField occupation;
    private javax.swing.JTextField openingBalance;
    // End of variables declaration//GEN-END:variables
}
